# Generated by Django 3.2.9 on 2021-11-28 21:50

import Store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(validators=[Store.validators.validate_nonzero]),
        ),
    ]
